config/routes.rb
Wordcloud::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config


  match '/auth/:provider/callback' => 'sessions#callback'
  match '/signin'    => 'sessions#index',   :as => :signin
  match "/signout"  => "sessions#destroy",  :as => :signout

  resources :themes, :except => %w(edit update) do
    resources :answers, :only => %w(index new create)
  end

  # static pages ::trick
  resources :pages, :except => %w(:show)

  root :to => "themes#index"

  # static pages ::trick
  get ':id', to: 'pages#show', :as => :page
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :comment, :theme_id, :ip, :user_id

  belongs_to :theme, :counter_cache => true, :autosave => true
end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :source, :permalink

  validates_uniqueness_of :permalink
end

app/models/theme.rb
class Theme < ActiveRecord::Base
  attr_accessible :image, :name, :answers_count
  mount_uploader :image, ThemeUploader

  validates :image,
            :presence => true

  after_initialize :default_value

  def default_value
    self.answers_count ||= 0
  end

  has_many :answers, :dependent => :destroy
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :provider, :screen_name, :uid

  has_many :themes

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.screen_name = auth["info"]["nickname"]
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  # GET /answers
  # GET /answers.json
  def index
    @theme = Theme.find(params[:theme_id])
    @answers = @theme.answers.select('count(*) count, comment').group(:comment)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @answers }
    end
  end

  # GET /answers/new
  # GET /answers/new.json
  def new
    @theme = Theme.find(params[:theme_id])
    @answer = @theme.answers.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @answer }
    end
  end

  # POST /answers
  # POST /answers.json
  def create
    @theme = Theme.find(params[:theme_id])

    @answer = @theme.answers.build(params[:answer])
    @answer.ip = request.remote_ip
    @answer.user_id = current_user.id if current_user.present?

    respond_to do |format|
      if @answer.save
        format.html { redirect_to theme_answers_path(theme_id: @theme.id), notice: 'Answer was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/pages_controller.rb
class PagesController < InheritedResources::Base
  def show
    begin
      @page = Page.find_by_permalink(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to root_url and return
    end

    @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def callback
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_filter :authenticate?, :except => %w(index)

  # GET /themes
  # GET /themes.json
  def index
    if params[:q].present?
      @themes = Theme.where(
          :id =>
              Answer.where("comment like ?", "%#{params[:q]}%").select('DISTINCT theme_id').pluck(:theme_id)
      ).order("answers_count DESC").page(params[:page]).per(20)
    else
      @themes = Theme.scoped.order("answers_count DESC").page(params[:page]).per(20)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @themes }
    end
  end

  # GET /themes/1
  # GET /themes/1.json
  def show
    @theme = Theme.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @theme }
    end
  end

  # GET /themes/new
  # GET /themes/new.json
  def new
    @theme = Theme.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @theme }
    end
  end

  # POST /themes
  # POST /themes.json
  def create
    @theme = current_user.themes.build(params[:theme])

    respond_to do |format|
      if @theme.save
        format.html { redirect_to @theme, notice: 'Theme was successfully created.' }
        format.json { render json: @theme, status: :created, location: @theme }
      else
        format.html { render action: "new" }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /themes/1
  # DELETE /themes/1.json
  def destroy
    @theme = Theme.find(params[:id])

    redirect_to root_url, flash: { error: "something went to wrong" } and return if @theme.user != current_user

    @theme.destroy

    respond_to do |format|
      format.html { redirect_to themes_url }
      format.json { head :no_content }
    end
  end

private
  def authenticate?
    if current_user.nil?
      redirect_to signin_path and return
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def shallow_args(parent, child)
    child.try(:new_record?) ? [parent, child] : child
  end

  def key_to_bs(key)
    case key.to_s
      when "alert" then
        return "alert"
      when "error" then
        return "error"
      when "notice" then
        return "success"
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/answers/_form.html.erb
<%= form_for( shallow_args(@theme, @answer) ) do |f| %>
  <div class="field">
    <%= f.label :comment, "コメントを入力してください" %><br />
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit nil, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/answers/index.html.erb
<div class="container-fluid">
	<div class="row-fluid">
		<div class="span12 tc">
			<span class="thumb rel">
			  <%= link_to new_theme_answer_path(theme_id: @theme.id), class: "animate-item" do %>
          <div class="hover">
            <span>回答する</span>
          </div>

		      <%= image_tag @theme.image.thumb.url, class: "base" %>
			  <% end %>
			</span>
		</div>
	</div>

	<hr/>

	<div class="row-fluid">
	  <div class="span12 wordcloud-wrap">
      <%- @answers.each do |answer| -%>
	      <%= link_to answer.comment, themes_path(q: answer.comment), class: "wordcloud", data: { count: answer.count } -%>
	    <%- end -%>
    </div>
	</div>
</div>

app/views/answers/new.html.erb
<div class="container-fluid">
	<div class="row-fluid">
		<div class="span12 tc">
			<span class="thumb">
			  <%= image_tag @theme.image.thumb.url %>
			</span>
		  <hr/>
		  <%= render 'form' %>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Wordcloud" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,200' rel='stylesheet' type='text/css'>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
	        <%= link_to "Word Cloud", root_url, class: "brand" %>
          <div class="container-fluid nav-collapse">
            <ul class="nav pull-right" id="main-menu-right">
            <% if current_user.present? %>
		          <li class="hello">Hello! <strong><%= current_user.screen_name %></strong></li>
              <li><%= link_to signout_path do %>SIGN OUT <i class="icon-share-alt"></i><% end %></li>
		        <% else %>
              <li><%= link_to signin_path do %>SIGN IN <i class="icon-share-alt"></i><% end %></li>
            <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <%= yield %>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span12">

	        <hr/>

		      <footer>
			      <span class="h28">
			        <a href="https://twitter.com/share" class="twitter-share-button" data-url="http://wordcloud-mosson.sqale.jp/" data-text="印象を文字で読み解く遊びアプリ" data-via="cucation" data-lang="ja">ツイート</a>
			        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
			      </span>

			      <span class="h28">
			        <iframe src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2Fwordcloud-mosson.sqale.jp%2F&amp;send=false&amp;layout=button_count&amp;width=100&amp;show_faces=false&amp;font=segoe+ui&amp;colorscheme=light&amp;action=like&amp;height=21&amp;appId=152863774861921" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:100px; height:21px;" allowTransparency="true"></iframe>
			      </span>

			      <span class="h28">
			        &copy; mosson 2012
			      </span>
		      </footer>
	      </div>
	    </div>
    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :source %><br />
    <%= f.text_area :source %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table>
  <tr>
    <th>Source</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pages.each do |page| %>
  <tr>
    <td><%= page.source %></td>
    <td><%= link_to 'Show', page %></td>
    <td><%= link_to 'Edit', edit_page_path(page) %></td>
    <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<%= raw @markdown.render(@page.source) %>

app/views/themes/_form.html.erb
<%= form_for @theme, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :image, :class => 'control-label' %>
    <div class="controls">
	    <%= f.file_field :image %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                themes_path, :class => 'btn' %>
  </div>
<% end %>

app/views/themes/index.html.erb
<div class="title-board">
  <div class="container-fluid">
    <% flash.each do |key,msg| %>
      <div class="alert alert-<%= key_to_bs(key) %>">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong><%= key.to_s.titleize %>!</strong> <%= msg %>
      </div>
    <% end %>

    <div class="row-fluid">
      <div class="span9">
        <h1>Sight the Insights</h1>
        <p>これはコメントから印象を掘り起こしてみる遊びアプリです</p>
      </div>
      <div class="span3">
	      <% if current_user.present? %>
          <%= link_to new_theme_path, class:"block-link" do %>
            画像を投稿する
          <% end %>
		    <% else %>
          <%= link_to signin_path, class:"block-link" do %>
	          ソーシャルログインして<br/>画像を投稿してみる
	        <% end %>
		    <% end %>
      </div>
    </div>
  </div>
</div>

<div class="container-board">

  <% if params[:q].present? %>
    <h4><em><%= params[:q] %></em>を含むもの</h4>
    <hr/>
  <% end %>

  <div class="row-fluid">
    <div class="span7"><%= paginate @themes %></div>
    <div class="span5 tr">
		  <%= form_tag(themes_path, method: :get, style: "margin: 20px 0px") do %>
	      <label class="s">ワードから検索: <input type="text" class="search-query" name="q" placeholder="Search"></label>
		  <% end %>
    </div>
  </div>

  <div id="container">
    <% @themes.each do |theme| %>
      <div class="box">
        <div class="image">
          <%= link_to new_theme_answer_path(theme_id: theme.id), class: "animate-item" do %>
            <div class="hover">
              <span>回答する</span>
            </div>

            <%= image_tag theme.image.thumb, class: "base" %>
          <% end %>
        </div>
        <div class="menu">
          <span class="count"><%= "#{theme.answers.count} answers"  %></span>
          <%= link_to theme_answers_path(theme_id: theme.id) do %>
            <i class="icon-eye-open"></i>
          <% end %>
		      <% if current_user == theme.user %>
	          <%= link_to theme_path(theme), method: :delete, data: { confirm: "Are you sure?"} do %>
	            <i class="icon-trash"></i>
	          <% end %>
		      <% end %>
        </div>
      </div>
    <% end %>
  </div>

  <%= paginate @themes %>
</div>

app/views/themes/new.html.erb
<div class="container-fluid">
  <% if @theme.errors.any? %>
		<div class="row-fluid">
		  <div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <strong>Error!</strong> <%= @theme.errors.full_messages.join(",") %>
      </div>
		</div>
  <% end %>

	<div class="row-fluid">
	  <%- model_class = Theme -%>
	  <div class="page-header">
	    <h4><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
	                                   :default => "New #{model_class.model_name.human}") %></h4>
	  </div>
	  <%= render :partial => 'form' %>
	</div>
</div>

app/views/themes/show.html.erb
<div class="container-fluid">
	<div class="row-fluid">

	  <% flash.each do |key,msg| %>
	    <div class="alert alert-<%= key_to_bs(key) %>">
	      <button type="button" class="close" data-dismiss="alert">×</button>
	      <strong><%= key.to_s.titleize %>!</strong> <%= msg %>
	    </div>
	  <% end %>

	  <%- model_class = Theme -%>
	  <div class="page-header">
	    <h4><%=t '.title', :default => model_class.model_name.human %></h4>
	  </div>

	  <dl class="dl-horizontal">
	    <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
	    <dd><%= @theme.name %></dd>
	    <dt><strong><%= model_class.human_attribute_name(:image) %>:</strong></dt>
	    <dd><%= image_tag @theme.image.thumb.url %></dd>
	  </dl>

	  <div class="form-actions">
	    <%= link_to t('.back', :default => t("helpers.links.back")),
	                themes_path, :class => 'btn'  %>
	    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
	                theme_path(@theme),
	                :method => 'delete',
	                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
	                :class => 'btn btn-danger' %>
	  </div>

	</div>
</div>